name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Setup PSE
      uses: invisirisk/pse-action@latest
      with:
        api_url: "https://app.dev.veribom.com"
        app_token: ${{secrets.IR_API_KEY}}
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
    - run: npm ci
    - name: Cleanup PSE
      if: always()
      uses: invisirisk/pse-action@latest
      with:
        cleanup: "true"
    - name: Gather Job status
      if: always()
      uses: invisirisk/pse-action@latest
      with:
        get_jobs: "true"